# Render.com configuration for easy deployment
services:
  - type: web
    name: pydantic-mcp-server
    runtime: python
    buildCommand: pip install -e .
    startCommand: python -c "from src.mcp_local_rag.simple_http_server import run_server; run_server()"
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8001
      - key: HOST  
        value: 0.0.0.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      # MCP_API_KEY should be set as an environment variable in Render dashboard